version: '3'
  
services:
        selenium:
                image: selenium/standalone-firefox:81.0 
                shm_size: 1g
                ports:
                        - "4444:4444"
                environment:
                    - GRID_TIMEOUT=120
                    - GRID_MAX_SESSION=200
                    - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
                    - GRID_BROWSER_TIMEOUT=120

